name: Amihub
title: Internet Marketing, Web Developer & Online Business Tutorial
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Amihub is a website that provides tutorial about SEO, Internet Marketing &amp; Webmaster.
  Learn easily how to find traffic, make money and create website..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amihub.com" # the base hostname & protocol for your site, e.g. http://example.com
cdn: "//cdn.amihub.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
timezone: Asia/Jakarta
permalink: /:categories/:title/
markdown: kramdown
minify_html: true
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
