title: Internet Marketing, Web Developer & Online Business Tutorial
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amihub.com" # the base hostname & protocol for your site, e.g. http://example.com
cdn: "//cdn.amihub.com/"
twitter_username: amihub
instagram_username:  amihubs

permalink: /:categories/:title/
# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
